# Generated by Django 4.2.4 on 2023-08-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(db_index=True, max_length=30, unique=True)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
